CREATE TABLE IF NOT EXISTS identity_owner (
    id UUID PRIMARY KEY,
    username VARCHAR(64) NOT NULL UNIQUE,
    password_hash VARCHAR(512) NOT NULL,
    created_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS identity_credentials (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    owner_id UUID NOT NULL REFERENCES identity_owner(id),
    kind VARCHAR(32) NOT NULL,
    token_hash VARCHAR(128) NOT NULL UNIQUE,
    expires_at TIMESTAMP WITH TIME ZONE NOT NULL,
    revoked_at TIMESTAMP WITH TIME ZONE NULL
);

CREATE INDEX IF NOT EXISTS identity_credentials_owner_idx ON identity_credentials(owner_id);
CREATE INDEX IF NOT EXISTS identity_credentials_active_idx ON identity_credentials(token_hash, revoked_at, expires_at);

CREATE TABLE IF NOT EXISTS identity_pairings (
    id UUID PRIMARY KEY,
    owner_id UUID NOT NULL REFERENCES identity_owner(id),
    code_hash VARCHAR(128) NOT NULL UNIQUE,
    expires_at TIMESTAMP WITH TIME ZONE NOT NULL,
    consumed_at TIMESTAMP WITH TIME ZONE NULL,
    created_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP
);
