CREATE TABLE IF NOT EXISTS agent_sessions (
    id UUID PRIMARY KEY,
    owner_id UUID NOT NULL,
    title TEXT,
    summary TEXT,
    status VARCHAR(32) NOT NULL DEFAULT 'idle',
    phase VARCHAR(64) NOT NULL DEFAULT 'idle',
    run_state TEXT NOT NULL DEFAULT '{}',
    last_trace TEXT NOT NULL DEFAULT '[]',
    pending_confirmation TEXT,
    context_usage TEXT,
    created_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP
);
ALTER TABLE agent_sessions ADD COLUMN IF NOT EXISTS title TEXT;
ALTER TABLE agent_sessions ADD COLUMN IF NOT EXISTS summary TEXT;
CREATE INDEX IF NOT EXISTS agent_sessions_owner_idx ON agent_sessions(owner_id, updated_at DESC);

CREATE TABLE IF NOT EXISTS agent_messages (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    session_id UUID NOT NULL REFERENCES agent_sessions(id) ON DELETE CASCADE,
    owner_id UUID NOT NULL,
    role VARCHAR(32) NOT NULL,
    content TEXT,
    reasoning TEXT,
    tool_name VARCHAR(128),
    arguments_json TEXT,
    parsed_json TEXT,
    context_source VARCHAR(256),
    context_kind VARCHAR(64),
    created_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP
);
CREATE INDEX IF NOT EXISTS agent_messages_session_idx ON agent_messages(session_id, id);

CREATE TABLE IF NOT EXISTS agent_replays (
    session_id UUID NOT NULL REFERENCES agent_sessions(id) ON DELETE CASCADE,
    tool_name VARCHAR(128) NOT NULL,
    arguments_json TEXT NOT NULL,
    output TEXT,
    parsed_json TEXT,
    created_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY (session_id, tool_name, arguments_json)
);

CREATE TABLE IF NOT EXISTS agent_events (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    session_id UUID NOT NULL REFERENCES agent_sessions(id) ON DELETE CASCADE,
    event_name VARCHAR(64) NOT NULL,
    event_data TEXT NOT NULL DEFAULT '{}',
    created_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP
);
CREATE INDEX IF NOT EXISTS agent_events_session_idx ON agent_events(session_id, id);

CREATE TABLE IF NOT EXISTS agent_nonces (
    session_id UUID NOT NULL REFERENCES agent_sessions(id) ON DELETE CASCADE,
    nonce VARCHAR(256) NOT NULL,
    consumed_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY (session_id, nonce)
);
