"""存储抽象：业务代码只依赖此协议，可平滑切换 local / S3。"""
from __future__ import annotations

from typing import Any, Protocol


class Storage(Protocol):
    def list_dir(self, rel_path: str = "") -> list[dict[str, Any]]: ...
    def read_text(self, rel_path: str, max_chars: int = 8000) -> str: ...
    def save_bytes(self, rel_path: str, data: bytes) -> dict[str, Any]: ...
    def mkdir(self, rel_path: str) -> None: ...
    def rename(self, src: str, dst: str) -> None: ...
    def move(self, src: str, dst_dir: str) -> None: ...
    def delete(self, rel_path: str) -> None: ...
    def exists(self, rel_path: str) -> bool: ...
    def stat(self, rel_path: str) -> dict[str, Any]: ...
    def disk_usage(self) -> dict[str, int]: ...
    def resolve(self, rel_path: str) -> Any: ...
