"""存储抽象：业务代码只依赖此协议，可平滑切换 local / S3。"""
from __future__ import annotations

from pathlib import Path
from typing import Any, BinaryIO, Protocol


class Storage(Protocol):
    def list_dir(self, rel_path: str = "") -> list[dict[str, Any]]: ...
    def read_text(self, rel_path: str, max_chars: int = 8000) -> str: ...
    def create_temp_file(self) -> tuple[Path, BinaryIO]: ...
    def publish_temp(self, rel_path: str, temp_path: Path | str, exclusive: bool = False) -> dict[str, Any]: ...
    def save_bytes(self, rel_path: str, data: bytes, exclusive: bool = False) -> dict[str, Any]: ...
    def mkdir(self, rel_path: str) -> None: ...
    def rename(self, src: str, dst: str) -> None: ...
    def move(self, src: str, dst_dir: str) -> None: ...
    def delete(self, rel_path: str) -> None: ...
    def exists(self, rel_path: str) -> bool: ...
    def current_revision(self, rel_path: str) -> str | None: ...
    def write_text(self, rel_path: str, content: str) -> dict[str, Any]: ...
    def append_text(self, rel_path: str, content: str) -> dict[str, Any]: ...
    def copy(self, src: str, dst: str) -> dict[str, Any]: ...
    def stat(self, rel_path: str) -> dict[str, Any]: ...
    def disk_usage(self) -> dict[str, int]: ...
    def resolve(self, rel_path: str) -> Any: ...
